/* eslint-disable prettier/prettier */
import { name as appName } from '../../app.json';

export const STRING_CONSTANTS = {
    // common
    app_name: appName,
    homeText: 'Home',
    debitCardText: 'Debit Card',
    paymentText: 'Payment',
    creditText: 'Credit',
    profileText: 'Profile',
    testingText: 'Just the good stuff! Coming soon.',
    showCardNumberText: 'Show card number',
    hideCardNumberText: 'Hide card number',
    availableBalanceText: 'Available balance',
    symbRsText: 'S$',
    amountText: '3,000',
    cardHolderNameText: 'Mark Henry',
    cardNumText: '5647    3411    2413    2020',
    secretCardNumText: '●●●●    ●●●●    ●●●●    2020',
    expiryText: 'Thru: 12/20',
    cvvText: 'CVV: 456',
    topUpAccountText: 'Top-up account',
    topUpAccountDescText: 'Deposit money to your account to use with card',
    weeklySpendingLimitText: 'Weekly spending limit',
    weeklySpendingLimitDescText: 'You haven’t set any spending limit on card',
    freezeCardText: 'Freeze card',
    freezeCardDescText: 'Your debit card is currently active',
    deactivatedCardsText: 'Deactivated cards',
    deactivatedCardsDescText: 'Your previously deactivated cards',
    getANewCardText: 'Get a new card',
    getANewCardDescText: 'This deactivates your current debit cards',
    debitCardSpendingLimitText: 'Debit card spending limit',
    saveText: 'Save',
    setWeeklySpendingLimitText: 'Set a weekly debit card spending limit',
    setWeeklySpendingLimitDescText: 'Here weekly means the last 7 days - not the calendar week',
};
